# Generated by Django 5.0.2 on 2024-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Fecha_Retiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
